sudo: required
services:
  - docker

before_install:
  - docker build -t avin/docker-react -f Dockerfile.dev .

script:
  - docker run avin/docker-react npm run test -- --coverage

deploy:
  provider: elasticbeanstalk
  regoin: 'ap-northeast-1'
  app: 'docker'
  env: 'Docker-env'
  bucket_name: 'elasticbeanstalk-ap-northeast-1-381389287489'
  bucket_path: 'docker'
  on:
    branch: master
  access_key_id: $AWS_ACCESS_KEY
  secret_access_key:
    secure: '$AWS_SECRET_KEY'
