sudo: required
services:
  - docker

before_install:
  - docker build -t avin/docker-react -f Dockerfile.dev . --build-arg proxy ""

script:
  - docker run avin/docker-react npm run test -- --coverage
